# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af9f7c958d72ec4011dc281ea03c26124081490287cc000692cf72824d2d6e69f4bfa418445a949983fa45cea1d16cf6cfde44971c9a9df004780bd9db908205

test:
  secret_key_base: 7162dc4b6acf293db1e62e0a8935191d8d4c09a5622485a79c0c3dbe2b3168f99c16c131368c6463736b4b77e55e696e3844dce2e792459260911eee86fc49d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
